# Generated by Django 4.2.15 on 2024-08-08 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_pending_final_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes'),
        ),
    ]
