# Generated by Django 4.2.15 on 2024-08-09 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_booking_is_pending_final_checked_booking_qr_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='is_pending_final_checked',
            new_name='paid',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='pending_final',
            new_name='payment_due',
        ),
    ]
